item {
  id: 1
  display_name: "Audi"
}
item {
  id: 2
  display_name: "Citroen"
}
item {
  id: 3
  display_name: "GMC"
}
item {
  id: 4
  display_name: "Honda"
}
item {
  id: 5
  display_name: "Hyundai"
}
item {
  id: 6
  display_name: "Infiniti"
}
item {
  id: 7
  display_name: "Mazda"
}
item {
  id: 8
  display_name: "Mercedes"
}
item {
  id: 9
  display_name: "Mitsubishi"
}
item {
  id: 10
  display_name: "Nissan"
}
item {
  id: 11
  display_name: "Renault"
}
item {
  id: 12
  display_name: "Toyota"
}
item {
  id: 13
  display_name: "Volkswagen"
}
item {
  id: 14
  display_name: "bmw"
}
item {
  id: 15
  display_name: "cadillac"
}
item {
  id: 16
  display_name: "chevrolet"
}
item {
  id: 17
  display_name: "ford"
}
item {
  id: 18
  display_name: "jeep"
}
item {
  id: 19
  display_name: "kia"
}
item {
  id: 20
  display_name: "lexus"
}
item {
  id: 21
  display_name: "mini"
}
item {
  id: 22
  display_name: "porsche"
}
item {
  id: 23
  display_name: "ram"
}
item {
  id: 24
  display_name: "range-rover"
}
item {
  id: 25
  display_name: "subaru"
}
item {
  id: 26
  display_name: "suzuki"
}
item {
  id: 27
  display_name: "volvo"
}
